### PR TITLE
fix $db->prefix.'groups to $db->prefix.'`groups`

### PR DESCRIPTION
**Pull request by iznogoud59**
Hi,
In my database, i've not a prefix.
A error occured because the  reserved 'groups' word is not escape by backtick.
I've fixed it now.

### CODE REVIEW

**Comment by iznogoud59** [comment]
Oops! I went too fast.
Thanks for the feedback.
Fixed!

**Comment by Vizzielli** [comment]
> Oops! I went too fast.
Thanks for the feedback.
Fixed!

np

**Comment by MioVisman** [comment]
It's a bad idea to use apostrophes. FluxBB is used not only with MySQL.

If tables have already been created, then

1. set a prefix in your config.php file, exemle $db_prefix = 'forum_';
2. add this prefix to all tables in your database

**Comment by MioVisman** [comment]
Strange GitHub behavior. I mentioned this pull request in the commit, GithHub closed it after that on its own.

**Pull request closed without merging**
